### ISSUE TITLE
[Assignment-02] Code Review

### ISSUE THREAD

**Issue by youngkwon02** [LikeLion-at-CAU-10th/Minseo-Kim#1]
https://github.com/LikeLion-at-CAU-10th/Minseo-Kim/blob/d2ef9f439cb1fa709e0a5efd8c53413aa56c844e/assignment/assignment-02/Q2/style2.css#L111-L116

민서도 마찬가지로 flex-basis가 경우에 따라 width 또는 height에 적용되기 때문에, 조금 더 명시적으로 사용하기 위해서는 width, height으로 값을 주는게 좋을거같아.
아래처럼~

```css
 .layout3-five { 
     display: flex; 
     justify-content: center; 
     width: 100%; 
     height: 100%; 
 } 
```
